#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
# Source0 file verified with key 0x4C09DD83CAAA50B2 (ajax@nwnk.net)
#
Name     : bdftopcf
Version  : 1.1
Release  : 8
URL      : https://xorg.freedesktop.org/archive/individual/app/bdftopcf-1.1.tar.bz2
Source0  : https://xorg.freedesktop.org/archive/individual/app/bdftopcf-1.1.tar.bz2
Source99 : https://xorg.freedesktop.org/archive/individual/app/bdftopcf-1.1.tar.bz2.sig
Summary  : No detailed summary available
Group    : Development/Tools
License  : MIT-Opengroup
Requires: bdftopcf-bin = %{version}-%{release}
Requires: bdftopcf-license = %{version}-%{release}
Requires: bdftopcf-man = %{version}-%{release}
BuildRequires : pkgconfig(xorg-macros)
BuildRequires : xorgproto-dev
Patch1: CVE-2017-16611.patch

%description
bdftopcf is a font compiler for the X server and font server.  Fonts
in Portable Compiled Format can be read by any architecture, although
the file is structured to allow one particular architecture to read
them directly without reformatting.  This allows fast reading on the
appropriate machine, but the files are still portable (but read more
slowly) on other machines.

%package bin
Summary: bin components for the bdftopcf package.
Group: Binaries
Requires: bdftopcf-license = %{version}-%{release}

%description bin
bin components for the bdftopcf package.


%package license
Summary: license components for the bdftopcf package.
Group: Default

%description license
license components for the bdftopcf package.


%package man
Summary: man components for the bdftopcf package.
Group: Default

%description man
man components for the bdftopcf package.


%prep
%setup -q -n bdftopcf-1.1
%patch1 -p1

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C
export SOURCE_DATE_EPOCH=1557081859
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
export CFLAGS="$CFLAGS -O3 -fcf-protection=full -ffat-lto-objects -flto=4 -fstack-protector-strong "
export FCFLAGS="$CFLAGS -O3 -fcf-protection=full -ffat-lto-objects -flto=4 -fstack-protector-strong "
export FFLAGS="$CFLAGS -O3 -fcf-protection=full -ffat-lto-objects -flto=4 -fstack-protector-strong "
export CXXFLAGS="$CXXFLAGS -O3 -fcf-protection=full -ffat-lto-objects -flto=4 -fstack-protector-strong "
%configure --disable-static
make  %{?_smp_mflags}

%check
export LANG=C
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
make VERBOSE=1 V=1 %{?_smp_mflags} check

%install
export SOURCE_DATE_EPOCH=1557081859
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/bdftopcf
cp COPYING %{buildroot}/usr/share/package-licenses/bdftopcf/COPYING
%make_install

%files
%defattr(-,root,root,-)

%files bin
%defattr(-,root,root,-)
/usr/bin/bdftopcf

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/bdftopcf/COPYING

%files man
%defattr(0644,root,root,0755)
/usr/share/man/man1/bdftopcf.1
