#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
# Source0 file verified with key 0x4C09DD83CAAA50B2 (ajax@nwnk.net)
#
Name     : bdftopcf
Version  : 1.1
Release  : 4
URL      : https://xorg.freedesktop.org/archive/individual/app/bdftopcf-1.1.tar.bz2
Source0  : https://xorg.freedesktop.org/archive/individual/app/bdftopcf-1.1.tar.bz2
Source99 : https://xorg.freedesktop.org/archive/individual/app/bdftopcf-1.1.tar.bz2.sig
Summary  : No detailed summary available
Group    : Development/Tools
License  : MIT-Opengroup
Requires: bdftopcf-bin
Requires: bdftopcf-doc
BuildRequires : fontsproto-dev
BuildRequires : pkgconfig(xorg-macros)
BuildRequires : xproto-dev

%description
bdftopcf is a font compiler for the X server and font server.  Fonts
in Portable Compiled Format can be read by any architecture, although
the file is structured to allow one particular architecture to read
them directly without reformatting.  This allows fast reading on the
appropriate machine, but the files are still portable (but read more
slowly) on other machines.

%package bin
Summary: bin components for the bdftopcf package.
Group: Binaries

%description bin
bin components for the bdftopcf package.


%package doc
Summary: doc components for the bdftopcf package.
Group: Documentation

%description doc
doc components for the bdftopcf package.


%prep
%setup -q -n bdftopcf-1.1

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C
export SOURCE_DATE_EPOCH=1510235643
%configure --disable-static
make V=1  %{?_smp_mflags}

%check
export LANG=C
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
make VERBOSE=1 V=1 %{?_smp_mflags} check

%install
export SOURCE_DATE_EPOCH=1510235643
rm -rf %{buildroot}
%make_install

%files
%defattr(-,root,root,-)

%files bin
%defattr(-,root,root,-)
/usr/bin/bdftopcf

%files doc
%defattr(-,root,root,-)
%doc /usr/share/man/man1/*
